<?php

namespace RestoBundle\Repository;

/**
 * CommandeSaladeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeSaladeRepository extends \Doctrine\ORM\EntityRepository
{
}
